# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FiveIosDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FiveIosDemo

  target 'FiveIosDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FiveIosDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#集成 flutter
flutter_application_path = '/Users/zhangrong/WorkDv/GitAppProject/FlutterDv/FiveTest2/flutter_module/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)